steps:
   # Step 0: configure git
  - name: 'gcr.io/cloud-builders/git'
    args: ['config', 'pull.rebase', 'true']
   
   # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Capstone-Projects-2023-Fall/project-bereal-meets-slack.git', 'main']

  # Step 2: Install Node.js and npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'main'  # Set the working directory to the cloned repository

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - touch main/.env

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - echo $$env > main/.env
    secretEnv: ['env']

availableSecrets:
   secretManager: 
     - versionName: 'projects/380272145905/secrets/env/versions/latest'
       env: 'env'
    

timeout: '900s'  # Set a timeout for the build in seconds
