steps:
   # Step 0: configure git
  - name: 'gcr.io/cloud-builders/git'
    args: ['config', 'pull.rebase', 'true']
   
   # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Capstone-Projects-2023-Fall/project-bereal-meets-slack.git', 'main']

  # Step 2: Install Node.js and npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'source'  # Set the working directory to the cloned repository

  # Step 3: Run the Node.js application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['start']
    dir: 'source'  # Set the working directory to the cloned repository

timeout: '900s'  # Set a timeout for the build in seconds
