steps:
   # Step 0: configure git
  - name: 'gcr.io/cloud-builders/git'
    args: ['config', 'pull.rebase', 'true']
   
   # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Capstone-Projects-2023-Fall/project-bereal-meets-slack.git', 'app']

  # Step 2: Install Node.js and npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'app'  # Set the working directory to the cloned repository


  # Step 3: create .env
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - touch app/.env

  # Step 4: fill out .env from the secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - echo -e $$env > app/.env
    secretEnv: ['env']

  # Step 5: create DockerFile
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - touch app/Dockerfile

  # Step 6: fill out DockerFile
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - echo -e "FROM node:18\n\nCOPY package.json /app/package.json\nWORKDIR /app\nRUN npm install\n\nCOPY . /app\n\nCMD [\"npm\", \"run\", \"startdev\"]" > app/Dockerfile

  # Step 7: Build a docker image using the code.  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/berealbot/berealbotdeploy/deployimage', '.']
    dir: 'app'
    
  # Step 8: Push the Docker container to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/berealbot/berealbotdeploy/deployimage']
  
  # Step 9: Update deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - berealbot
      - '--platform=managed'
      - >-
        --image=us-central1-docker.pkg.dev/berealbot/berealbotdeploy/deployimage
      - '--region=us-central1'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

options:
   logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/berealbot/secrets/env/versions/latest
    env: 'env'

images:
   - 'us-central1-docker.pkg.dev/berealbot/berealbotdeploy/deployimage'

timeout: '900s'  # Set a timeout for the build in seconds
