steps:
   # Step 0: configure git
  - name: 'gcr.io/cloud-builders/git'
    args: ['config', 'pull.rebase', 'true']
   
   # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Capstone-Projects-2023-Fall/project-bereal-meets-slack.git', 'app']

  # Step 2: Install Node.js and npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'app'  # Set the working directory to the cloned repository

  # Step 3: create .env
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - touch app/.env

  # Step 4: fill out .env from the secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - echo $$env > app/.env
    secretEnv: ['env']

  # Step 5: create DockerFile
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - touch app/DockerFile

  # Step 6: fill out DockerFile
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - echo -e "FROM node:18\n\nCOPY package.json /app/package.json\nWORKDIR /app\nRUN npm install\n\nCOPY . /app\n\nCMD ["node", "start"]" > app/DockerFile
    secretEnv: ['env']

  # Step 5: Build a docker image using the code.  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/berealbot/berealbotdeploy', '.']
    dir: 'app'
    
  # Step 6: Push the Docker container to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/berealbot/berealbotdeploy']

availableSecrets:
   secretManager: 
     - versionName: 'projects/380272145905/secrets/env/versions/latest'
       env: 'env'

images:
   - 'gcr.io/berealbot/berealbotdeploy'

timeout: '900s'  # Set a timeout for the build in seconds
